package ru.boilercalc.app.core.theme

import androidx.compose.ui.graphics.Color

// ═══ Dark Theme ═══
val DarkPrimary = Color(0xFF1E88E5)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkPrimaryContainer = Color(0xFF1565C0)
val DarkOnPrimaryContainer = Color(0xFFBBDEFB)
val DarkSecondary = Color(0xFFA5D6A7)
val DarkOnSecondary = Color(0xFF1B5E20)
val DarkSecondaryContainer = Color(0xFF2E7D32)
val DarkOnSecondaryContainer = Color(0xFFC8E6C9)
val DarkTertiary = Color(0xFFFFC107)
val DarkOnTertiary = Color(0xFF3E2723)
val DarkTertiaryContainer = Color(0xFFF57F17)
val DarkOnTertiaryContainer = Color(0xFFFFF8E1)
val DarkError = Color(0xFFFF5252)
val DarkOnError = Color(0xFFFFFFFF)
val DarkBackground = Color(0xFF161B22)
val DarkOnBackground = Color(0xFFD1D5DB)
val DarkSurface = Color(0xFF1F2630)
val DarkOnSurface = Color(0xFFD1D5DB)
val DarkSurfaceVariant = Color(0xFF2E3A4A)
val DarkOnSurfaceVariant = Color(0xFF7B9BB5)
val DarkOutline = Color(0xFF2E3A4A)

// ═══ Light Theme ═══
val LightPrimary = Color(0xFF1565C0)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFBBDEFB)
val LightOnPrimaryContainer = Color(0xFF0D47A1)
val LightSecondary = Color(0xFF4CAF50)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFC8E6C9)
val LightOnSecondaryContainer = Color(0xFF1B5E20)
val LightTertiary = Color(0xFFFF9800)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFFE0B2)
val LightOnTertiaryContainer = Color(0xFFE65100)
val LightError = Color(0xFFD32F2F)
val LightOnError = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFFAFAFA)
val LightOnBackground = Color(0xFF1A1A2E)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1A1A2E)
val LightSurfaceVariant = Color(0xFFF5F5F5)
val LightOnSurfaceVariant = Color(0xFF49454F)
val LightOutline = Color(0xFFCAC4D0)

// ═══ Latte Theme ═══
val LattePrimary = Color(0xFF8B6914)
val LatteOnPrimary = Color(0xFFFFFFFF)
val LattePrimaryContainer = Color(0xFFFFDEA1)
val LatteOnPrimaryContainer = Color(0xFF5D4200)
val LatteSecondary = Color(0xFF6B8E23)
val LatteOnSecondary = Color(0xFFFFFFFF)
val LatteSecondaryContainer = Color(0xFFD4E6A5)
val LatteOnSecondaryContainer = Color(0xFF3B5500)
val LatteTertiary = Color(0xFFCD853F)
val LatteOnTertiary = Color(0xFFFFFFFF)
val LatteTertiaryContainer = Color(0xFFFFDCC2)
val LatteOnTertiaryContainer = Color(0xFF6B3A00)
val LatteError = Color(0xFFBA1A1A)
val LatteOnError = Color(0xFFFFFFFF)
val LatteBackground = Color(0xFFFAF6F0)
val LatteOnBackground = Color(0xFF3E2C1C)
val LatteSurface = Color(0xFFF0E8DC)
val LatteOnSurface = Color(0xFF3E2C1C)
val LatteSurfaceVariant = Color(0xFFE8DDD0)
val LatteOnSurfaceVariant = Color(0xFF6B5D4F)
val LatteOutline = Color(0xFFD4C5B0)
